# Generated by Django 2.2.26 on 2022-02-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoretracker', '0003_column_row'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='value',
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
